on:
  schedule:
    - cron: '45 8 * * *'
  workflow_dispatch:

jobs:
  main:
    uses: EricTendian/runbooks/.github/workflows/update-meta-gbp.yml@main
    with:
      dists-json: '["bionic"]'
    secrets: inherit
